# SAE Evaluation

In [19]:
import pandas as pd

## Down 2.0

In [20]:
down20_res = pd.read_csv(
    "../results/sae_evaluation/reconstruction/assessment_20250822_204604/unet_down_blocks_2_attentions_0/step_488282/results.csv"  # noqa:E501
)
down20_res

,sae_name,sae_path,target_module,seed,dead_features_pct,reconstruction_lpips,reconstruction_mean_manhattan,reconstruction_median_manhattan,reconstruction_r2,fid_score,avg_timestep_r2
0,step_488282,../../checkpoints/sae/down_blocks.2.attentions...,unet.down_blocks.2.attentions.0,42,0.0,0.477246,0.150735,0.098447,0.369388,51.125248,"{0: np.float64(0.2959919126033783), 1: np.floa..."
1,step_488282,../../checkpoints/sae/down_blocks.2.attentions...,unet.down_blocks.2.attentions.0,43,0.0,0.513129,0.155929,0.103306,0.363194,51.037804,"{0: np.float64(0.2983934618830681), 1: np.floa..."
2,step_488282,../../checkpoints/sae/down_blocks.2.attentions...,unet.down_blocks.2.attentions.0,44,0.0,0.473213,0.158936,0.101929,0.365999,48.296375,"{0: np.float64(0.2932420068383217), 1: np.floa..."
3,step_488282,../../checkpoints/sae/down_blocks.2.attentions...,unet.down_blocks.2.attentions.0,45,0.0,0.487458,0.152123,0.102259,0.364221,51.150764,"{0: np.float64(0.3008377019762993), 1: np.floa..."
4,step_488282,../../checkpoints/sae/down_blocks.2.attentions...,unet.down_blocks.2.attentions.0,46,0.0,0.507577,0.140982,0.096161,0.367280,51.470055,"{0: np.float64(0.3049728279709816), 1: np.floa..."

In [ ]:
down20_res.drop(
    columns=["sae_name", "sae_path", "target_module", "avg_timestep_r2"],
    inplace=True,
)

In [28]:
# Compute mean and std for every metric

mean_values = down20_res.mean()
std_values = down20_res.std()

formatted_results_down20 = {}
for col in down20_res.columns:
    if "r2" in col:
        # Format as percentage with 2 decimal places
        formatted_results_down20[col] = (
            f"{mean_values[col] *100:.3f} ± {std_values[col] * 100:.3f}%"
        )
    else:
        # Format with 6 decimal places for other metrics
        formatted_results_down20[col] = (
            f"{mean_values[col]:.3f} ± {std_values[col]:.3f}"
        )

# Create DataFrame for display
down_20_df = pd.DataFrame([formatted_results_down20])
down_20_df

,seed,dead_features_pct,reconstruction_lpips,reconstruction_mean_manhattan,reconstruction_median_manhattan,reconstruction_r2,fid_score
0,44.000 ± 1.581,0.000 ± 0.000,0.492 ± 0.018,0.152 ± 0.007,0.100 ± 0.003,36.602 ± 0.246%,50.616 ± 1.307

## Up.1.1