# SAE Evaluation

In [2]:
import pandas as pd

## Down 2.0

### Reconstruction

#### Low-Resolution (512x512)

In [3]:
down20_df = pd.read_csv(
    "../results/sae_evaluation/reconstruction/assessment_20250822_204604/unet_down_blocks_2_attentions_0/step_488282/results.csv"  # noqa:E501
)
down20_df

,sae_name,sae_path,target_module,seed,dead_features_pct,reconstruction_lpips,reconstruction_mean_manhattan,reconstruction_median_manhattan,reconstruction_r2,fid_score,avg_timestep_r2
0,step_488282,../../checkpoints/sae/down_blocks.2.attentions...,unet.down_blocks.2.attentions.0,42,0.0,0.477246,0.150735,0.098447,0.369388,51.125248,"{0: np.float64(0.2959919126033783), 1: np.floa..."
1,step_488282,../../checkpoints/sae/down_blocks.2.attentions...,unet.down_blocks.2.attentions.0,43,0.0,0.513129,0.155929,0.103306,0.363194,51.037804,"{0: np.float64(0.2983934618830681), 1: np.floa..."
2,step_488282,../../checkpoints/sae/down_blocks.2.attentions...,unet.down_blocks.2.attentions.0,44,0.0,0.473213,0.158936,0.101929,0.365999,48.296375,"{0: np.float64(0.2932420068383217), 1: np.floa..."
3,step_488282,../../checkpoints/sae/down_blocks.2.attentions...,unet.down_blocks.2.attentions.0,45,0.0,0.487458,0.152123,0.102259,0.364221,51.150764,"{0: np.float64(0.3008377019762993), 1: np.floa..."
4,step_488282,../../checkpoints/sae/down_blocks.2.attentions...,unet.down_blocks.2.attentions.0,46,0.0,0.507577,0.140982,0.096161,0.367280,51.470055,"{0: np.float64(0.3049728279709816), 1: np.floa..."

In [4]:
down20_df.drop(
    columns=["sae_name", "sae_path", "target_module", "avg_timestep_r2"],
    inplace=True,
)

In [ ]:
# Compute mean and std for every metric

mean_values = down20_df.mean()
std_values = down20_df.std()

formatted_results_down20 = {}
for col in down20_df.columns:
    if "r2" in col:
        # Format as percentage with 2 decimal places
        formatted_results_down20[col] = (
            f"{mean_values[col] *100:.2f} ± {std_values[col] * 100:.2f}%"
        )
    else:
        formatted_results_down20[col] = (
            f"{mean_values[col]:.3f} ± {std_values[col]:.3f}"
        )

# Create DataFrame for display
down20_res = pd.DataFrame([formatted_results_down20])
down20_res

,seed,dead_features_pct,reconstruction_lpips,reconstruction_mean_manhattan,reconstruction_median_manhattan,reconstruction_r2,fid_score
0,44.000 ± 1.581,0.000 ± 0.000,0.492 ± 0.018,0.152 ± 0.007,0.100 ± 0.003,36.602 ± 0.246%,50.616 ± 1.307

#### High-Resolution (768x768)

In [6]:
down20_df_high = pd.read_csv(
    "../results/sae_evaluation/reconstruction/assessment_20250825_162118/unet_down_blocks_2_attentions_0/step_488282/results.csv"  # noqa:E501
)

In [7]:
down20_df_high.drop(
    columns=["sae_name", "sae_path", "target_module", "avg_timestep_r2"],
    inplace=True,
)

In [8]:
mean_values = down20_df_high.mean()
std_values = down20_df_high.std()

formatted_results_down20_high = {}
for col in down20_df.columns:
    if "r2" in col:
        # Format as percentage with 2 decimal places
        formatted_results_down20_high[col] = (
            f"{mean_values[col] *100:.3f} ± {std_values[col] * 100:.3f}%"
        )
    else:
        # Format with 6 decimal places for other metrics
        formatted_results_down20_high[col] = (
            f"{mean_values[col]:.3f} ± {std_values[col]:.3f}"
        )

down_20_res_high = pd.DataFrame([formatted_results_down20_high])
down_20_res_high

,seed,dead_features_pct,reconstruction_lpips,reconstruction_mean_manhattan,reconstruction_median_manhattan,reconstruction_r2,fid_score
0,44.000 ± 1.581,0.000 ± 0.000,0.410 ± 0.011,0.104 ± 0.007,0.067 ± 0.005,36.481 ± 0.435%,45.454 ± 0.350

In [9]:
formatted_results_down20_high

{'seed': '44.000 ± 1.581',
 'dead_features_pct': '0.000 ± 0.000',
 'reconstruction_lpips': '0.410 ± 0.011',
 'reconstruction_mean_manhattan': '0.104 ± 0.007',
 'reconstruction_median_manhattan': '0.067 ± 0.005',
 'reconstruction_r2': '36.481 ± 0.435%',
 'fid_score': '45.454 ± 0.350'}

### Knockout

In [10]:
down20_knockout_df = pd.read_csv(
    "../results/sae_evaluation/feature_removal/assessment_20250823_162012/unet_down_blocks_2_attentions_0/step_488282/results.csv"
)  # noqa: E501
metrics = ["lpips", "mean_manhattan", "median_manhattan", "fid"]
intervals = ["0-9", "10-19", "20-24"]

summary = []
for interval in intervals:
    for metric in metrics:
        col = f"removal_{interval}_{metric}"
        summary.append(
            {
                "interval": interval,
                "metric": metric,
                "mean": down20_knockout_df[col].mean(),
                "std": down20_knockout_df[col].std(),
                "mean±std": f"{down20_knockout_df[col].mean():.3f} ± {down20_knockout_df[col].std():.3f}",  # noqa: E501
            }
        )

down20_knockout_results_df = pd.DataFrame(summary)
print(
    down20_knockout_results_df.pivot(
        index="metric", columns="interval", values="mean±std"
    )
)

interval                     0-9           10-19           20-24
metric
fid               58.066 ± 1.814  49.624 ± 2.237  23.806 ± 2.277
lpips              0.580 ± 0.015   0.272 ± 0.016   0.105 ± 0.014
mean_manhattan     0.187 ± 0.009   0.079 ± 0.002   0.038 ± 0.001
median_manhattan   0.131 ± 0.004   0.044 ± 0.002   0.022 ± 0.001

## Up.1.1

### Reconstruction

#### Low Resolution (512x512)

In [11]:
up11_df = pd.read_csv(
    "../results/sae_evaluation/reconstruction/assessment_20250822_204604/unet_up_blocks_1_attentions_1/step_488282/results.csv"  # noqa:E501
)
up11_df

,sae_name,sae_path,target_module,seed,dead_features_pct,reconstruction_lpips,reconstruction_mean_manhattan,reconstruction_median_manhattan,reconstruction_r2,fid_score,avg_timestep_r2
0,step_488282,../../checkpoints/sae/up_blocks.1.attentions.1...,unet.up_blocks.1.attentions.1,42,0.0,0.431647,0.136088,0.084125,0.395776,49.036640,"{0: np.float64(0.3395538141131401), 1: np.floa..."
1,step_488282,../../checkpoints/sae/up_blocks.1.attentions.1...,unet.up_blocks.1.attentions.1,43,0.0,0.470070,0.140678,0.088133,0.388131,50.541302,"{0: np.float64(0.3351432095170021), 1: np.floa..."
2,step_488282,../../checkpoints/sae/up_blocks.1.attentions.1...,unet.up_blocks.1.attentions.1,44,0.0,0.428347,0.143420,0.086659,0.393791,46.036270,"{0: np.float64(0.3281553284525871), 1: np.floa..."
3,step_488282,../../checkpoints/sae/up_blocks.1.attentions.1...,unet.up_blocks.1.attentions.1,45,0.0,0.435542,0.135906,0.085435,0.394369,48.606400,"{0: np.float64(0.3446314859986305), 1: np.floa..."
4,step_488282,../../checkpoints/sae/up_blocks.1.attentions.1...,unet.up_blocks.1.attentions.1,46,0.0,0.454823,0.126405,0.081224,0.399410,49.074417,"{0: np.float64(0.3518430603146553), 1: np.floa..."

In [12]:
up11_df.drop(
    columns=["sae_name", "sae_path", "target_module", "avg_timestep_r2"],
    inplace=True,
)

In [ ]:
# Compute mean and std for every metric

mean_values = up11_df.mean()
std_values = up11_df.std()

formatted_results_up11 = {}
for col in up11_df.columns:
    if "r2" in col:
        # Format as percentage with 2 decimal places
        formatted_results_up11[col] = (
            f"{mean_values[col] *100:.2f} ± {std_values[col] * 100:.2f}%"
        )
    else:
        formatted_results_up11[col] = (
            f"{mean_values[col]:.3f} ± {std_values[col]:.3f}"
        )

# Create DataFrame for display
up11_res = pd.DataFrame([formatted_results_up11])
up11_res

,seed,dead_features_pct,reconstruction_lpips,reconstruction_mean_manhattan,reconstruction_median_manhattan,reconstruction_r2,fid_score
0,44.000 ± 1.581,0.000 ± 0.000,0.444 ± 0.018,0.136 ± 0.006,0.085 ± 0.003,39.430 ± 0.408%,48.659 ± 1.639

#### High Resolution (768x768)

In [ ]:
up11_df_high = pd.read_csv(
    "../results/sae_evaluation/reconstruction/assessment_20250825_162118/unet_up_blocks_1_attentions_1/step_488282/results.csv"  # noqa: E501
)

In [24]:
up11_df_high.drop(
    columns=["sae_name", "sae_path", "target_module", "avg_timestep_r2"],
    inplace=True,
)

In [ ]:
# Compute mean and std for every metric
mean_values = up11_df_high.mean()
std_values = up11_df_high.std()

formatted_results_up11_high = {}
for col in up11_df_high.columns:
    if "r2" in col:
        # Format as percentage with 2 decimal places
        formatted_results_up11_high[col] = (
            f"{mean_values[col] *100:.2f} ± {std_values[col] * 100:.2f}%"
        )
    else:
        formatted_results_up11_high[col] = (
            f"{mean_values[col]:.3f} ± {std_values[col]:.3f}"
        )

# Create DataFrame for display
up11_res_high = pd.DataFrame([formatted_results_up11_high])
up11_res_high

,seed,dead_features_pct,reconstruction_lpips,reconstruction_mean_manhattan,reconstruction_median_manhattan,reconstruction_r2,fid_score
0,44.000 ± 1.581,0.000 ± 0.000,0.361 ± 0.011,0.092 ± 0.006,0.055 ± 0.004,40.30 ± 0.45%,43.771 ± 0.802

### Knockout

In [ ]:
up11_knockout_df = pd.read_csv(
    "../results/sae_evaluation/feature_removal/assessment_20250823_162012/unet_up_blocks_1_attentions_1/step_488282/results.csv"
)  # noqa: E501
metrics = ["lpips", "mean_manhattan", "median_manhattan", "fid"]
intervals = ["0-9", "10-19", "20-24"]

summary = []
for interval in intervals:
    for metric in metrics:
        col = f"removal_{interval}_{metric}"
        summary.append(
            {
                "interval": interval,
                "metric": metric,
                "mean": up11_knockout_df[col].mean(),
                "std": up11_knockout_df[col].std(),
                "mean±std": f"{up11_knockout_df[col].mean():.3f} ± {up11_knockout_df[col].std():.3f}",  # noqa: E501
            }
        )

up11_knockout_results_df = pd.DataFrame(summary)
print(
    up11_knockout_results_df.pivot(
        index="metric", columns="interval", values="mean±std"
    )
)

interval                     0-9           10-19           20-24
metric
fid               60.281 ± 1.278  53.282 ± 1.735  24.249 ± 1.501
lpips              0.554 ± 0.015   0.288 ± 0.015   0.101 ± 0.008
mean_manhattan     0.171 ± 0.010   0.082 ± 0.003   0.039 ± 0.002
median_manhattan   0.116 ± 0.006   0.046 ± 0.001   0.022 ± 0.001